# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arx < Formula
  desc "Architecture audit CLI for cross-language codebases"
  homepage "https://github.com/pauvalls/arx"
  version "0.35.0"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pauvalls/arx/releases/download/v0.35.0/arx_0.35.0_darwin_amd64.zip"
      sha256 "35bffca1d0ef507daf017977237285b0ebafd33ff60bf058cb30e2ac762b0cde"

      define_method(:install) do
        bin.install "arx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pauvalls/arx/releases/download/v0.35.0/arx_0.35.0_darwin_arm64.zip"
      sha256 "d11714fad1b5bf642865c516b60ad8ffd331355b22772be1ae2ccf46db95784f"

      define_method(:install) do
        bin.install "arx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pauvalls/arx/releases/download/v0.35.0/arx_0.35.0_linux_amd64.tar.gz"
      sha256 "02012bd96cca482dcf805bdbca21b3be16d3ad21ffd46b31f28aefcb8eb20138"
      define_method(:install) do
        bin.install "arx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pauvalls/arx/releases/download/v0.35.0/arx_0.35.0_linux_arm64.tar.gz"
      sha256 "6f11053ce38fb5c86d4fea0befe8d2304c1fa0fbdbbadc64740f1156443e0650"
      define_method(:install) do
        bin.install "arx"
      end
    end
  end

  test do
    system "#{bin}/arx --version"
  end
end
